# -*- coding: utf-8 -*-
"""TALLER_N_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/142K54mULkuU8CHiyMBc4EpHqBOkQrryx
"""

cardinalidad_U=int(input("Por favor ingrese la cardinalidad del cojunto U:"))
cardinalidad_A=int(input("Por favor ingrese la cardinalidad del conjunto A:"))

conjunto_U= set()
conjunto_A= set()

print(f"Ingrese {cardinalidad_U} elementos únicos para el conjunto U:")
while len(conjunto_U) < cardinalidad_U:
    elemento = input(f"Elemento {len(conjunto_U)+1} de U: ")
    if elemento in conjunto_U:
        print("Este elemento ya fue ingresado. Ingrese un valor diferente.")
    else:
        conjunto_U.add(elemento)

print(f"\nIngrese {cardinalidad_A} elementos del conjunto A (deben pertenecer a U):")
while len(conjunto_A) < cardinalidad_A:
    elemento = input(f"Elemento {len(conjunto_A)+1} de A: ")
    if elemento in conjunto_A:
        print("Este elemento ya fue ingresado en A. Intente con otro.")
    elif elemento not in conjunto_U:
        print("Este elemento no pertenece al conjunto U. Intente con uno válido.")
    else:
        conjunto_A.add(elemento)

# Mostrar los conjuntos finales
print("\n Conjuntos ingresados:")
print("Conjunto U:", conjunto_U)
print("Conjunto A:", conjunto_A)
U = list(conjunto_U)
A = list(conjunto_A)

# 1) Calcular U - A
U_menos_A = []
for elem in U:
    if elem not in A:
        U_menos_A.append(elem)

# 2) Calcular (U - A) ⨁ A = [(U - A) ∪ A] - [(U - A) ∩ A]
# Unión (U - A) ∪ A
union = U_menos_A.copy()
for elem in A:
    if elem not in union:
        union.append(elem)

# Intersección (U - A) ∩ A
interseccion = []
for elem in U_menos_A:
    if elem in A:
        interseccion.append(elem)

# Diferencia simétrica = unión - intersección
diferencia_simetrica = []
for elem in union:
    if elem not in interseccion:
        diferencia_simetrica.append(elem)

# 3) Calcular (U ∩ A) - A

# Intersección U ∩ A
interseccion_U_A = []
for elem in U:
    if elem in A:
        interseccion_U_A.append(elem)

# Diferencia (U ∩ A) - A
diferencia_interseccion_A = []
for elem in interseccion_U_A:
    if elem not in A:
        diferencia_interseccion_A.append(elem)

# 4) Calcular (U ∪ A) ∩ A

# Unión U ∪ A
union_U_A = U.copy()
for elem in A:
    if elem not in union_U_A:
        union_U_A.append(elem)

# Intersección (U ∪ A) ∩ A
interseccion_union_A = []
for elem in union_U_A:
    if elem in A:
        interseccion_union_A.append(elem)

# Mostrar resultados
print("\nResultados:")
print("(U - A) ⨁ A =", diferencia_simetrica)
print("(U ∩ A) - A =", diferencia_interseccion_A)
print("(U ∪ A) ∩ A =", interseccion_union_A)