# -*- coding: utf-8 -*-
"""Taller_20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dDTQSNHnokPH1_BntbrMYsxMlTQ0WBbn
"""

import numpy as np
import matplotlib.pyplot as plt

# Datos
x = np.array([0, 1, 2, 3, 4, 5, 6, 7])
y = np.array([5.5, 5.4, 4.0, 3.7, 3.0, 2.0, 2.0, 1.5])

# Ajuste del polinomio de segundo grado
coeficientes = np.polyfit(x, y, 2)
a2, a1, a0 = coeficientes
print(f"Ecuación: y = {a2:.4f}x² + {a1:.4f}x + {a0:.4f}")

# Valores estimados
y_pred = np.polyval(coeficientes, x)

# Coeficiente de determinación (R²)
ss_res = np.sum((y - y_pred)**2)
ss_tot = np.sum((y - np.mean(y))**2)
R2 = 1 - (ss_res / ss_tot)

# Coeficiente de correlación (r)
r = np.sqrt(R2)

print(f"Coeficiente de determinación (R²): {R2:.4f}")
print(f"Coeficiente de correlación (r): {r:.4f}")

# Gráfica
x_continuo = np.linspace(min(x), max(x), 200)
y_continuo = np.polyval(coeficientes, x_continuo)

plt.scatter(x, y, color='red', label='Datos experimentales')
plt.plot(x_continuo, y_continuo, color='blue', label='Ajuste polinomial')
plt.title('Regresión Polinomial de Segundo Grado')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.grid(True)
plt.show()