# -*- coding: utf-8 -*-
"""Taller_21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PjXBzNA6gJsznWYGbhfhHaiFlzV7ONEn
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.array([0, 1, 2, 3, 4])
y = np.array([1, -0.5, -1, 2.5, 0.5])

def lagrange_interpolacion(xi, yi, x_eval):
    total = 0
    n = len(xi)
    for i in range(n):
        Li = 1
        for j in range(n):
            if i != j:
                Li *= (x_eval - xi[j]) / (xi[i] - xi[j])
        total += yi[i] * Li
    return total

x_continuo = np.linspace(min(x), max(x), 200)
y_continuo = [lagrange_interpolacion(x, y, xi) for xi in x_continuo]

x_eval = 2.5
y_eval = lagrange_interpolacion(x, y, x_eval)
print(f"Valor interpolado en x = {x_eval}: f(x) = {y_eval:.4f}")

plt.scatter(x, y, color='red', label='Puntos dados')
plt.plot(x_continuo, y_continuo, color='blue', label='Polinomio de Lagrange')
plt.title('Interpolación de Lagrange - Taller 21')
plt.xlabel('x')
plt.ylabel('f(x)')
plt.legend()
plt.grid(True)
plt.show()